

import { Inter } from "next/font/google";
import Header from "./src/component/Header/Header";
import Footer from "./src/component/Footer/Footer";
import "./src/component/Footer/Footer.css"
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer, toast } from 'react-toastify';
import ProviderRedux from "./src/component/ProviderRedux/ProviderRedux";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">




      <body className={inter.className}>
      <ProviderRedux>
        <Header></Header>
        </ProviderRedux>
        <main>
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous" />
          {children}
        </main>
       <Footer></Footer>
         <ToastContainer></ToastContainer>
      </body>
    </html>
  );
}
